const express = require('express');
const app = express();
const custom = require('./morgan-custom-function');
const logger = require('./logger');
const morgan = require('morgan');
const helmet = require('helmet');
const config = require('config');
const user = require('./async');
const User = new user();
const courses = require('./routes/courses');
const home = require('./routes/home');
const startupDebug = require('debug')('app:startup');
const dbDebugger = require('debug')('app:db');
console.log(`Application Name: ${config.get('name')}`);
console.log(`Application Mail Server: ${config.get('mail.host')}`);
console.log(`Application Mail Password: ${config.get('mail.password')}`);
app.set('view engine', 'pug');
app.set('views','./views');
app.use(express.json());
app.use(express.urlencoded({extended: true}));
app.use(express.static('public'));
app.use(logger);
app.use('/api/courses', courses);
app.use(home);
if(app.get('env')==='development'){
app.use(morgan(custom));
startupDebug('Morgan Enabled.......');
}
dbDebugger('Connected to database.....');
app.use(helmet());
const port = process.env.PORT || 3000;
app.listen(port,()=>{console.log(`Listening on port ${port}.....`)});
User.logUser();